#!/usr/bin/python2
#coding=utf-8
#Dev: Faxel

from subprocess import check_output
import os
from platform import system as systemos, architecture
from wget import download

def Ngrok_serveur():
    if True:
        if 'Android' in str(check_output(('uname', '-a'))) or 'arm' in str(check_output(('uname', '-a'))):
            nom_de_fichier = 'ngrok-stable-linux-arm.zip'
        else:
            os_type = systemos().lower()
            if architecture()[0] == '64bit':
                nom_de_fichier = 'ngrok-stable-{0}-amd64.zip'.format(os_type)
            else:
                nom_de_fichier = 'ngrok-stable-{0}-386.zip'.format(os_type)
        url = 'https://bin.equinox.io/c/4VmDzA7iaHb/' + nom_de_fichier
        download(url)
        os.system('unzip ' + nom_de_fichier)
        os.system('rm -rf ' + nom_de_fichier)
        os.system('clear')

def Localxpose_serveur(): 
    if True:
        if 'Android' in str(check_output(('uname', '-a'))) or 'arm' in str(check_output(('uname', '-a'))):
            nom_de_fichier = 'loclx-linux-arm.zip'
        else:
            type_os= systemos().lower()
            if architecture()[0] == '64bit':
                nom_de_fichier = 'loclx-linux-amd64.zip'.format(type_os)
            else:
                nom_de_fichier = 'loclx-linux-386.zip'.format(type_os)
        url = 'https://lxpdownloads.sgp1.digitaloceanspaces.com/cli/'+nom_de_fichier
        download(url)
        os.system('unzip loclx*.zip')
        os.system('rm loclx*.zip')
        os.system("mv loclx* loclx")
        os.system('clear')        

Ngrok_serveur()
Localxpose_serveur()
